### ISSUE TITLE
Error and edge case page UX

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#88]
Issue to cover the discussion and development of UX of the identified edge/error pages identified here: https://github.com/strimzi/strimzi-ui/tree/master/client/Pages#current-pages

As a part of the discussion, the defintion of a set of Gherkin based behaviours should be identified, which will be used as the base for acceptance testing.

This discussion may also identify other UI components required to enable these flows. These should be discussed/designed in their own issues.

**Comment by lboehling** [comment]
Adding some preliminary PF mocks for the three error states listed above. Will definitely need another pass on the copy for these error states. One thing to note: We often give users a link to report the issue if they think there is a bug. Since this is a community project, do we want to include a link to the repo on these error pages?

<img width="1359" alt="Screen Shot 2020-11-20 at 4 10 14 PM" src="https://user-images.githubusercontent.com/46571616/99850203-eedd8000-2b4a-11eb-8be6-8d24278c6539.png">

**Comment by chloepoulterdesign** [comment]
Here's some Carbon error states - just the ones listed in the document above, as Lucia has done. 
![image](https://user-images.githubusercontent.com/47979346/99982984-352d1c00-2da3-11eb-9b49-4dfd025b57d6.png)

I don't see a use-case for the "Not authorised" state in the first iteration of the UI, where topics are only listed on a page - which I have noted on the mockup, although, i'm sure the page will be useful in future.

**Comment by pmuir** [comment]
@lboehling I like the idea of including a link to the upstream repo issue tracker.

Unauthorized is unlikely to happen yet, I agree, as we will be forcing a login.
