### ISSUE TITLE
Page Header UX

### ISSUE THREAD

**Issue by matthew-chirgwin** [strimzi/strimzi-ui#89]
This issue is to cover the discussion and design of the UX for the Strimzi UI page header and its behaviour.

As a part of the discussion, the defintion of a set of Gherkin based behaviours should be identified, which will be used as the base for acceptance testing.

This discussion may also identify other UI components required to enable these flows. These should be discussed/designed in their own issues.

**Comment by matthew-chirgwin** [comment]
One behaviour to call out, depending on if security is on (or not). We may, or may not know who the user is (ie their name). Most headers tend to contain a 'user'/their name - we may not have this information in all cases

**Comment by chloepoulterdesign** [comment]
![image](https://user-images.githubusercontent.com/47979346/98812405-56dce980-241a-11eb-877e-c0a041200d9a.png)

Here's some initial thoughts. 
- we need to figure out what the available help/links to docs/links to slack might be required/included for Strimzi
- The newest profile menu pieces being worked on include the `Profile and settings` link which we probably wouldn't have any use for
- I've approximated a version for the `security off` case, however I'm not sure we'd even need the reduced amount I've included - we could just remove that item from the top navigation, or make it un-clickable...

**Comment by lboehling** [comment]
PF Mocks below
 
_Profile info available_ 
![Profile menu](https://user-images.githubusercontent.com/46571616/99849064-db311a00-2b48-11eb-806d-68a0e2db2310.png)

_No user info available_

- would there be any info relating to this user at all? I.e. role, permissions, etc.?

![Profile menu - no user info](https://user-images.githubusercontent.com/46571616/99849062-db311a00-2b48-11eb-88ec-bbfc5196772e.png)

_Help menu_
![Profile menu - settings icon](https://user-images.githubusercontent.com/46571616/99849063-db311a00-2b48-11eb-9914-4149d534afef.png)

_About modal accessed via help menu_

- not sure if this about modal is needed, but it was mentioned on the call yesterday. We would need some further discussion on what needs/should be included in the about modal. I've kept some PF defaults in this mock for now. 

![Nav - about modal](https://user-images.githubusercontent.com/46571616/99849060-db311a00-2b48-11eb-9ee6-7ebdf4f1fd6a.png)

**Comment by chloepoulterdesign** [comment]
## Cluster name
⚠️ @lboehling has raised a really good thought in her about modal page. We haven't included any way for the user to know an instance name/"server name"/cluster id in the UI designs so far. This doesn't necessarily need to be in the header but needs to be somewhere...?  
@matthew-chirgwin do we need a further Gherkin behaviour along the lines of `"as a user I can distinguish which Strimzi cluster my UI is attached to so that I can distinguish multiple clusters that I have open in a browser"?`
I've updated the designs below to include the cluster name in the header next to "Strimzi".

## Other revisions
Otherwise, here's a revision on my earlier designs:
### Variations on named, unnamed and insecured user profile menus
![image](https://user-images.githubusercontent.com/47979346/99981239-0d3cb900-2da1-11eb-8231-53d9ef810f03.png)

- I realised that according to Carbon guidelines being drafted around this profile menu, the "about" content should actually be launched there.
- It would be helpful to know what user info Keycloak returns - user name, image, email, etc etc? Is there is a link to their user profile we can include? I found [this](https://www.keycloak.org/docs-api/5.0/rest-api/index.html#_userrepresentation) but some help interpreting it would be good. 

### help menu
![image](https://user-images.githubusercontent.com/47979346/99981322-29d8f100-2da1-11eb-9c99-bdfb8ee233c5.png)
I think "Getting started" could direct link to here: https://strimzi.io/docs/operators/latest/quickstart.html#proc-using-amq-streams-str
I think "Documentation" could direct link to here: https://strimzi.io/documentation/
and I think "Community" could link to here: https://strimzi.io/community/

_Finally, I need some help copywriting for the about modal_
![image](https://user-images.githubusercontent.com/47979346/99981374-39583a00-2da1-11eb-8a04-7c061d6173e5.png)

**Comment by matthew-chirgwin** [comment]
> @matthew-chirgwin do we need a further Gherkin behaviour along the lines of `"as a user I can distinguish which Strimzi cluster my UI is attached to so that I can distinguish multiple clusters that I have open in a browser"?`

Absolutley - when the work is raised to implement these screens this should be covered

**Comment by chloepoulterdesign** [comment]
Outstanding questions:
- [ ] What user information are we getting back from Keycloak? Is there a “profile” page we can link to?
- [ ] Can PF display cluster name in the header too?
- [ ] Can someone do the copywriting for the “About” modal?

**Comment by pmuir** [comment]
What you get back from keycloak depends on the scope that you request, but it's probably safe to assume we can get the standard claims - `openid`, `profile` and `email` - which normally gives you (the useful subset) name, family name, given name, middle name, nickname, picture, email and email verified (boolean) e.g. https://openid.net/specs/openid-connect-basic-1_0.html#StandardClaims. There is a standard url for the users profile.

**Comment by chloepoulterdesign** [comment]
Ok, that's great & sounds like we should be able to achieve the photo, name etc I've specced above.
